In [6]:
import numpy
n = numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [8]:
n = n.reshape(3, 3, 3)
n

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
import cv2

In [12]:
print([i for i in n.flat])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


In [19]:
stack = numpy.hstack((n, n))
print(stack)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [18 19 20]
  [21 22 23]
  [24 25 26]]]


In [24]:
print(numpy.hsplit(stack, 3))


[array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[18, 19, 20],
        [21, 22, 23]]]), array([[[ 6,  7,  8],
        [ 0,  1,  2]],

       [[15, 16, 17],
        [ 9, 10, 11]],

       [[24, 25, 26],
        [18, 19, 20]]]), array([[[ 3,  4,  5],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[21, 22, 23],
        [24, 25, 26]]])]
